### ISSUE TITLE
Application Hub - error 503

### ISSUE THREAD

**Issue by blaziq** [EOEPCA/deployment-guide#42]
While the Deployment Guide explicitly says that in the current state i.e. without an OIDC provider (Keycloak) the Application Hub will not work, the actual result seems even more incorrect - see the screenshot below:
![image](https://github.com/user-attachments/assets/69a78473-aea2-4de6-a043-b3bea6923f98)

This happens for any URL: 
https://app-hub.eoepca-sciencehub.esa.int/hub/home
https://app-hub.eoepca-sciencehub.esa.int/hub/login 
etc.

One would expect that at least the basic pages will open correctly and only a login attempt will fail due to the lack of an OIDC provider. Instead, the component fails at the very basic level.

Logs from _application-hub-hub_:
```
[D 2024-11-25 16:32:23.556 JupyterHub pages:584] No template for 503
[I 2024-11-25 16:32:23.557 JupyterHub log:191] 200 GET /hub/error/503?url=%2Fhub%2Fhome (@10.42.89.121) 2.07ms
[D 2024-11-25 16:32:23.616 JupyterHub pages:584] No template for 503
[I 2024-11-25 16:32:23.617 JupyterHub log:191] 200 GET /hub/error/503?url=%2Fhub%2Fstatic%2Fcss%2Fstyle.min.css%3Fv%3D01598a5386176f0279952a3b9632a07e7fce9a12aa53108973c83be9ec3473e7a59354876fab64bfeb01892eb503870183707aa03f207d7a94845ca7980c3819 (@10.42.89.121) 1.91ms
[D 2024-11-25 16:32:23.620 JupyterHub pages:584] No template for 503
[I 2024-11-25 16:32:23.621 JupyterHub log:191] 200 GET /hub/error/503?url=%2Fhub%2Fstatic%2Fcomponents%2Fjquery%2Fdist%2Fjquery.min.js%3Fv%3Da6e981b23351186aa43f32879dd64c6801be6e2af7ef8b0e472cccdeeba52d5d7894de4bcb292a364f1e11e525524077534338140a72687ada4fae62849843a5 (@10.42.89.121) 3.24ms
[D 2024-11-25 16:32:23.621 JupyterHub pages:584] No template for 503
[I 2024-11-25 16:32:23.623 JupyterHub log:191] 200 GET /hub/error/503?url=%2Fhub%2Fstatic%2Fcomponents%2Frequirejs%2Frequire.js%3Fv%3Dbd1aa102bdb0b27fbf712b32cfcd29b016c272acf3d864ee8469376eaddd032cadcf827ff17c05a8c8e20061418fe58cf79947049f5c0dff3b4f73fcc8cad8ec (@10.42.89.121) 5.20ms
[D 2024-11-25 16:32:23.624 JupyterHub pages:584] No template for 503
[I 2024-11-25 16:32:23.625 JupyterHub log:191] 200 GET /hub/error/503?url=%2Fhub%2Fstatic%2Fcomponents%2Fbootstrap%2Fdist%2Fjs%2Fbootstrap.min.js%3Fv%3Da014e9acc78d10a0a7a9fbaa29deac6ef17398542d9574b77b40bf446155d210fa43384757e3837da41b025998ebfab4b9b6f094033f9c226392b800df068bce (@10.42.89.121) 7.02ms
[D 2024-11-25 16:32:23.625 JupyterHub pages:584] No template for 503
[I 2024-11-25 16:32:23.627 JupyterHub log:191] 200 GET /hub/error/503?url=%2Fhub%2Flogo (@10.42.89.121) 8.63ms
[D 2024-11-25 16:32:23.695 JupyterHub pages:584] No template for 503
[I 2024-11-25 16:32:23.696 JupyterHub log:191] 200 GET /hub/error/503?url=%2Fhub%2Fstatic%2Ffavicon.ico%3Fv%3Dfde5757cd3892b979919d3b1faa88a410f28829feb5ba22b6cf069f2c6c98675fceef90f932e49b510e74d65c681d5846b943e7f7cc1b41867422f0481085c1f (@10.42.89.121) 2.02ms
[D 2024-11-25 16:32:24.286 JupyterHub log:191] 200 GET /hub/health (@10.28.9.17) 0.63ms
[D 2024-11-25 16:32:26.287 JupyterHub log:191] 200 GET /hub/health (@10.28.9.17) 0.66ms
```
(this is what happens when an Application Hub page is loaded in the browser)

Also, describe of _application-hub-hub_:
```
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Warning  FailedScheduling        13m (x2 over 13m)  default-scheduler        0/4 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling..
  Normal   Scheduled               13m                default-scheduler        Successfully assigned application-hub/application-hub-hub-869d9bfc9c-njjks to eoepkak4
  Normal   SuccessfulAttachVolume  13m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-955d3f87-cd2e-4ae9-b39f-b3509c8ecf03"
  Normal   Pulling                 13m                kubelet                  Pulling image "eoepca/application-hub:1.2.0"
  Normal   Pulled                  13m                kubelet                  Successfully pulled image "eoepca/application-hub:1.2.0" in 969ms (969ms including waiting)
  Normal   Created                 13m                kubelet                  Created container hub
  Normal   Started                 13m                kubelet                  Started container hub
  Warning  Unhealthy               13m                kubelet                  Readiness probe failed: Get "http://10.42.89.120:8081/hub/health": dial tcp 10.42.89.120:8081: connect: connection refused
```

Also, logs from _application-hub-proxy_:
```
16:35:01.156 [ConfigProxy] error: 503 GET /hub/home Error: getaddrinfo ENOTFOUND application-hub-hub.default
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'application-hub-hub.default'
}
16:35:01.204 [ConfigProxy] error: 503 GET /hub/static/components/requirejs/require.js Error: getaddrinfo ENOTFOUND application-hub-hub.default
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'application-hub-hub.default'
}
16:35:01.205 [ConfigProxy] error: 503 GET /hub/static/css/style.min.css Error: getaddrinfo ENOTFOUND application-hub-hub.default
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'application-hub-hub.default'
}
16:35:01.236 [ConfigProxy] error: 503 GET /hub/static/components/jquery/dist/jquery.min.js Error: getaddrinfo ENOTFOUND application-hub-hub.default
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'application-hub-hub.default'
}
16:35:01.238 [ConfigProxy] error: 503 GET /hub/static/components/bootstrap/dist/js/bootstrap.min.js Error: getaddrinfo ENOTFOUND application-hub-hub.default
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'application-hub-hub.default'
}
16:35:01.240 [ConfigProxy] error: 503 GET /hub/logo Error: getaddrinfo ENOTFOUND application-hub-hub.default
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'application-hub-hub.default'
}
16:35:01.307 [ConfigProxy] error: 503 GET /hub/static/favicon.ico Error: getaddrinfo ENOTFOUND application-hub-hub.default
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'application-hub-hub.default'
}
```
(as above, happens when an Application Hub page is loaded in the browser)

**Comment by james-hinton** [comment]
I’ve refactored much of the Application Hub deployment configuration. The **503 error** was caused by an incorrect namespace reference in the Helm values, which resulted in the Application Hub components routing internally to the wrong location. I’ve fixed it in [this commit](https://github.com/EOEPCA/deployment-guide/commit/5ee26a80179bd67d31cb3d276bd6dd8aafa5c740#diff-b001b4882b6a3e016dfee864f0a16a1be022d6c0660a49e876f91494e35017aeR22)
